# load the required wallpaper to the memory
preload = /home/x9/Pictures/wallpapers/wallhaven-jexkwm_1920x1080.png

# set for a specific monitor 
wallpaper = ,/home/x9/Pictures/wallpapers/wallhaven-jexkwm_1920x1080.png


